language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
sudo: required
services:
- docker
notifications:
  email:
  - xy_tian@126.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: deWhQx+FXOmKWXDHG7ZTGlA0F/wz1IExL04AEM7a60Qr6sTbfEWxKKZke26DuLIHk3CTTDFNVf7G5H7jGGRF9TuNYhP1bd1DRMrVWPAl+JDTlbK7P3Y6TnKACBcxHrJBJ2rSbnZJeocMyTOaGufFvKr24gdsJpPro/jnMIDCVfIb8q6vQRFPz5YKe6oMeApY9Jhv9s16UO6K2svyXHeflQK9Ax0KDeSXBdbtEHKVsK8g54o+XV0jOSlwuNpZwdibpf7in0o2/YTDF0zaB1LdZQ/TpT4l0TEeBv4Ci/qiZxTA51WU7rQViOeyzy2OY1ZCFtC5/ekA8vTv55QxJ+KQjVoVQRPH9u4qUhBad7jVaKlaWu6MoldRLm9J1ewUdeJfp1h20qvbIYsyZhUt515XCkc6ad3Jb6TBiqtgNlRJwWTtmNSYyQ6OKnRz00M2DINll0gkv6h4rUdKR0hElqCYA2XZdhVCJLLo7lgjRdCUEScMrJHc8kwbQNmHvDTTRBj8ADknm4gjPFqorNSazhz64R3FwnOsjoXMrzz52a6tGBp1Cj6Uj82gCDX7GU8g8Fdr1eJh+u34q3tIrwJbBqZhDsBKjk1MW1h39PXLgii2FTUF6Yi8IbWB4UVMbYkV2b7GkXHFVTv9Kuux8g+E8cGAWX3KJTcNxFOJCRskHxEK4mI=
  - secure: I9y8VN+xCzghzeKjw+Gb3T5gD7hfprLeaI+sL4x4wjx79wFiSglklI9MxlqzVAf7CNIt09h0du9eoe6eZGjsP6yl/VSzuLegZeRSZGRyszwqsHawa0xcrAFVH+yJV2es5DkCIkgmi3q0BzsW9v6NfGHbNoUSoP9cwyuEvKP/HQz3OXMHKAurBIR3OMe87JIswIgRkirBThecImPyIT4+/yvBUPkfJBA0UFh0cI+Ot3902RaJcJyndalSnyK6fLEDLcchIkC/hvLBb4MZUV+aBcmbXch4R64xFXJjtZt9AcIlbqn4/fAaJqlJzN/FjnAE4UdPKjhKVnpuRFWJf1h7rRyeVYwAH8Ovdji7EOMjUuEChidR0Oiaf4cfWZhetNWG+jOlgceizGFf9TRgGe/TL7T4363ESYjEZJzrT0/XrSQkKL1J3I7kHedMO01Mv9wEAx6wsa+9HoXryo4mqG/58mhb+aJ8MSCNzcfiVwIAhGG+V/4X2OQbjJjUF/Y1XWPI6VU9GsI97UAjuXYDA/guC5Tcw5oezTVhl+vUIZAPLdn71Lj8HeNHWH++arA2RHD5ZpfV/RElpEkmx6kwEk/mQY2fecmG90oGpqHiH4vli4bZadfhE83EubbqLIURqdFhbAju471YHH0gdj9kjKJhow+M1/dWtuIGEEZINLlh2Qo=
  - secure: IXFg1nboRAI9wQp+GOGkNIuzFaUB+HRMpwReyqXFlKgjGHf8T9WMZBUpk7eS7EhI5SoNk8wJnVjbvw6DmQz4ZYqHy5F9DwoCHaf3nNuZyLqn2QuRDo/Lvl0of5Tarm7uYwssaayP9eYSwJpww723LSJlqFbpN1a0e6UqvQmKfWePM0c9TUB3X8ZOP1uSryqefBCIG9xA+kzHkU8FUrVDoJ1oWgChMBzRUptyPTs2BtuGwufHgbRipXFsarTHmFI+w3mpvafvR/Vzmw6Vigshi9Lvb7bRbmm+KICb7VFGsZnBYm7QxgQKGW2ngCBrK9/y5X9wOoTvXIISLpPKmXGH1FCY2b2joqW8kgJtO1mLmLABe2a32PsHE2p81WioQVi2Cd8mRGr1kQV6OUhKH9k+3bSyd2IrlPq2Dofox6hYCt/4gV7U9gT1tvktLQdSiq7XflQyAQYd+zFdp2YqoewWbRNdOAWO17m35u3wbLcML26EIeYcYXy/FZBiRyw3sprvtZ+WJ5wRzK5DaVCM6n7mCYunIZcjQP4CBu9l5Oqvg0xKrbrUyDUqmoKDlRaC1XcOGjPqLKwi63Bb9yckxqcq6bfOapuG6pO8w66OW7ErNYI0zrTHPYVI9xwZCObN6H0ufNLhYMNMZLTX/AyYjxNzZG2C14L4NQHCVCAisn4V4Kc=
  - secure: s9QEA3MDBYR9HtDgkMO5fM3jlBMAUphNfBs3D+ZJ3ckX2eD3MGMQ8KpMmCrCMTODZjaY2aq9VX27dPWys4fYDOjto6z0tOQ3NJ8IH4Wh3tVN+XU83JKONm5j6cLuh9u2OmW+bmdqmtlrP9qQPfrgaoK9Rn55MKDpl9TkgEOi8cglMhMffYCbKfiVeF5aGS1APY2Wrb+wCIHvKEqmTrbftdBoKePyvPxuLUddiZgYEeahKQiYkvHGRpEVFhKp3AQTI6DNIA2L6WjQOYJTF5qFAjv87jslJ7ADOZjlfCvkSF6EQGXCSiJlrLDU6OCWLUktT//AvsqG2fmhZOQmdkYLD47HeiIeH3DIsn9tKEDVa2+PlQ4+Yfyx/lu8soEBp0ANyUSVsYIgPqKWQS+WoOYfDeNTF9qqGORG0+5Lxrw3V8qMBreqXzjJ0BBFFQLSEwvA9m/vsMTxDzGUIq8x2poaAjvtbkf8EAG4eq6jzVx2ZmNiYiCVVxZP0w/hwopr1xhUKBq13m7yxaI6xMMvapnWxBybHHhvomAGf9zeasq8qqqHKZG6GG718FfIdCcJp5uAd0eHt6K6ws81wVUBJpB3f+SbIDBRat/quaHw0aZ9pgeE0aL/tX8rKfBCRvbBUEuW3SqXLYLn6745bViv9j3vNztOcYC/i8BAxkE5mN0I1i0=
  - secure: UL7CXMcHkxSypWi/cWVuLeiz2JJfyBilxSR+sJjVr+6FeTqrFPKO2lI3YULhzUevOZrG1/znimkTUD0ULDOTJH/jzin3tRE3IK6SZxcz1FL01tttAUNIHAUa3a7vhY+rpSruu1zoumflHa4sdtA9DkHicn3wXma+RdaeOrqkqfAGbnMzK45PRb6fV6XX/xxcTmp6Qv/sHlKgf8XN26SWV21Hkrh3eGgbpKuVCjbn1TjfAGNLMln5nsbsT3E5CSKIs9rBNLdHBsGT3ZZHdmUZZqxuTOxG7L3k17nNKKQX0N0FphDHLbg94KYNCbjSly3UxR80RfCTZGW2PbmlNf4B6X2tPqq0vFGQIgH81Fuq1xCpH29J/SwUzG3tT44e9toSt1lE6q59Yke+TrYS2ZDS9hrbuFAaMnM3lBVB4La+Xi1iwgbk8HlAYRBDZnyQ99gc8MMK+bnyZPVXLD3luN7GC555Th7TJlQkFiJCCW6fqhpT8otVghFokj69eHcHZhne0YXIe+ul2+3YNWE1wYTSKxzWmMY7OG1iacopDspb2temCjOIGH6OpgSC2ySJorGNJ6OCk7ygPbwdPvKknLmidwgVt4aRSgyO5v/TaJkR9AfLgG3wFP9jhxUI95RKAgEgvr0J+00OLvEyEWYiw02VHtSxoghbHNzZ77dfEyTcHOg=
before_install:
- gem install travis -v 1.8.9 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=52.194.214.179
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
- sh travis_scripts/trigger_platform_tests.sh